### ISSUE TITLE
whut?

### ISSUE THREAD

**Issue by glop102** [CMMCD/Snorlax#2]
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz

**Comment by CMMCD** [comment]
We are aware of the issue with Snorlax falling asleep during some calculations.

We have given him a gallon bucket filled with 5 hour energy to drink.
Hopefully this will resolve your issue.
