### ISSUE TITLE
Not O(1)

### ISSUE THREAD

**Issue by ohnx** [CMMCD/Snorlax#3]
Sorry to be the party pooper, but I don't think this is O(1) - there is a for loop here, making it O(n).

Of course, like in real production things, you could just use false advertising and say that this algorithm is O(1)! :smile:

**Comment by CMMCD** [comment]
The for loop is just in the method where your Snorlax speaks to you. The normal sort method is O(1) and has no for loop :)

**Comment by ohnx** [comment]
@CMMCD Ah, I get it now... The `sort()` function is the actual function that sorts :stuck_out_tongue_closed_eyes:
